[package]
name = "rspc-vercel-example"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
tokio = { version = "1", features = ["macros", "time"] }
serde_json = { version = "1.0.107", features = ["raw_value"] }
rspc = { path = "../..", features = ["vercel"] }
vercel_runtime = { version = "^1.1.0" }
async-stream = "0.3.5"
thiserror = { workspace = true }
serde = { workspace = true }
specta = { workspace = true }

[[bin]]
name = "rspc"
path = "api/rspc/[rspc].rs"
